Abdur-rahmaanJ/greenberry

To Do List

Here are some things that need to be done

Create To Do List

---

docs/greenberry.css
docs/index.html

As the title describe, fixed the font.

Improved the font for main page .

---

files/greenBerry.py

In order to make it work I also changed the syntax:
plot xpoint-xpoint-xpoint xtext, ypoint-ypoint-ypoint ytext
e.g plot 1-2.5-6 time[s], 30-60-75.75 path[m]
You can have as much points as you want and you can leave the text out.

Fixed issues with plotting

---

docs/changeLog.html
docs/fans.html
docs/greenberry.css
docs/syntax.html

Issue #36 solved.
Syntax page, Fans page and changelog page should have the logo.
Logo added to these pages.
Logo was a little bit large. It's resized now.

Resized logo and added in other pages

---

docs/changeLog.html
docs/fans.html
docs/greenberry.css
docs/syntax.html

Reverts Abdur-rahmaanJ/greenBerry#37

Revert "Resized logo and added in other pages"

---

docs/changeLog.html
docs/fans.html
docs/syntax.html

pages added to:
- changeLog.html
- fans.html
- syntax.html

added logo to all pages under navigation bar

---

greenberry/gbtest/test.py

- currently catches the error
- there is a problem with the import statement files.greenberry as tests are not able to run properly, I am not sure about this fix.
- next step: fix errors and add more tests

added null test for eval function

---

greenberry/gbtools/lexer.py
greenberry/utils.py

File name is utils.py .It consists of two function ,
1)Infix to postfix convertor in which mathematical expression is taken as input.
2)Postfix Evaluation to give result.
Please test it and let me know if any issues.
P.S.Do read the comments in the code .

utils.py file for postfix evaluation

---

greenberry/gbtest/test.py

- resolved by importing module from parent directory using sys.append

fixed module import error

---

greenberry/gbtest/test.py

- was able to get the test to read from stdout to get the printed message from greenBerry_eval function.
- this form of testing might be a possible way for the future creation of tests.
- let me know!

added new test for simple addition eval function

---

greenberry/utils.py

InfixCon function  now takes a string as parameter ,earlier it was taking input inside it .

Postfix Evaluation

---

grammar.txt

For issue #31 -- I pretty much overhauled grammar.txt, mostly based on the website version. Let me know what you think!

Grammar update

---

greenberry/gb_ide.py

Add search function to IDE

---

code_running_instructions.md

a simple guide as to how can someone use the ide

i have added the file code_running_instructions.md for the issue #58, please review it

---

docs/css/style.css
docs/index.html
docs/js/script.js

Let me know what you think of this update

A dark mode for the index page

---

src/greenberry/symbols/__init__.py
src/greenberry/symbols/symbols.py
src/greenberry/utils/lex.py
src/greenberry/utils/print.py

fixed the issue along with one more issue that was , greenberry.symbols  , error issue E class was missing from init.py in symbols directory it was importing all the symbols from there.

fixed Issue#82 , cannot print eval expression with spaces in between

---

src/greenberry/gb.py
src/greenberry/utils/search.py

fixed the issue of with of print followed by any keyword , and also Error messages issues now error message would be appropriately displayed ,previously they were missing making it fail and python's exception was taking up the play 
now it's going to be greenberry's error messages, also fixed "call" keyword functionality

fixed print make error along with multiple keyword fails

---

src/greenberry/gb.py

i am not really sure of where to put the function , how many list comprehensions are there so i am just fixing this one , keep merging committing into this as i found them further or you could just give me the list

fixed issue#81 clean list comprehensions

---

src/greenberry/utils.py
tests/lang_test.py
tests/utils_test.py

Reverts Abdur-rahmaanJ/greenberry#93

Revert "Refactoring and Enhanced capture_print Function "

---

.gitignore
src/greenberry/gb.py
src/greenberry/symbols/symbols.py
src/greenberry/utils/class_instance.py

Classes can now be instantiated like this:
```
new obj_name, Class_name
```
```
class Man:power = 10 action walk: print walking...
new Jimmy, Man
```
See, add, and make still work just the same with instantiated classes, just use the objects name rather than the class name
```
add to Jimmy action run : print running...
make Jimmy run
Output:
running...
add to Jimmy attribute cool = 10
see cool of Jimmy
Output:
['10', 'number']
```
Also added syntax errors and undefined errors.

Non-static classes
